yarnPath: .yarn/releases/yarn-4.0.2.cjs
nodeLinker: node-modules

packageExtensions:
  '@conform-to/zod@^0.9.1':
    peerDependencies:
      '@conform-to/dom': ^0.9.1
    dependencies:
      '@conform-to/dom': ^0.9.1
